<?php
//liste des docTypes HAL
$DOCTYPE_LISTE = array(
'ART' =>'Articles',
'COMM' =>'Conference papers',
'COUV' =>'Book chapters',
'DOUV' =>'Proceedings, Book Editions',
'ETABTHESE' =>'Theses',
'HDR' =>'HDR',
'IMG' =>'Images',
'LECTURE' =>'Lectures',
'MAP' =>'Maps',
'MEM' =>'Dissertations',
'NOTE' =>'Notes',
'OTHER' =>'Others',
'OTHERREPORT' =>'Other reports',
'OUV' =>'Books',
'PATENT' =>'Patents',
'POSTER' =>'Posters',
'PRESCONF' =>'Conference papers (Files)',
'REPACT' =>'Annual reports',
'REPORT' =>'Reports',
'SOFTWARE' =>'Softwares',
'SON' =>'Sounds',
'SYNTHESE' =>'Syntheses',
'THESE' =>'PhD Theses',
'UNDEFINED' =>'Preprints',
'VIDEO' =>'Videos'
);

/*
$DOCTYPE_LISTE = array(
'ART' =>'Articles',
'COMM' =>'Communications',
'COUV' =>'Book chapter',
'DOUV' =>'Project management',
'ETABTHESE' =>'EtabThese ???',
'HDR' =>'Empowerment to direct research',
'IMG' =>'Picture',
'LECTURE' =>'Lecture ???',
'MAP' =>'Map',
'MEM' =>'Mem ???',
'NOTE' =>'Note',
'OTHER' =>'Other',
'OTHERREPORT' =>'Other report',
'OUV' =>'Book',
'PATENT' =>'Patent',
'POSTER' =>'Poster',
'PRESCONF' =>'Presconf ???',
'REPACT' =>'???',
'REPORT' =>'???',
'REPORT_COOR' =>'???',
'REPORT_DOCT' =>'???',
'REPORT_ETAB' =>'???',
'REPORT_FORM' =>'???',
'REPORT_FPROJ' =>'???',
'REPORT_GLICE' =>'???',
'REPORT_GMAST' =>'???',
'REPORT_LABO' =>'???',
'REPORT_LICE' =>'???',
'REPORT_LPRO' =>'???',
'REPORT_MAST' =>'???',
'REPORT_RETABINT' =>'???',
'REPORT_RFOINT' =>'???',
'SOFTWARE' =>'Software',
'SON' =>'Sound ???',
'SYNTHESE' =>'Synthesis',
'THESE' =>'PhD',
'UNDEFINED' =>'Undefined',
'VIDEO' =>'Video'
);
*/
?>