<?php
//liste des 'correspondances codes collection <> noms des unités'
$CODCOLL_LISTE = array(
"CRAPE" =>"ARENES - Centre de recherches sur l'action politique en Europe (ARENES)",
"BIOSIT" =>"Biosit - Structure Fédérative de Recherche en Biologie Santé",
"U835" =>"BRM - ARN régulateurs bactériens et médecine (BRM)",
"PN" =>"CAPHI - Centre Atlantique de Philosophie (CAPHI)",
"CDA-PR" =>"CDA - Centre de droit des affaires (CDA)",
"CIC" =>"CIC Rennes - Centre d'investigation clinique de Rennes",
"CNGC" =>"Comportement et noyaux gris centraux",
"OSS" =>"COSS - Chemistry, Oncogenesis, Stress and Signaling (COSS)",
"CREAAH" =>"CReAAH - Centre de recherche en archéologie, archéosciences, histoire (CReAAH)",
"CREM" =>"CREM - Centre de recherche en économie et management (CREM)",
"ECOBIO" =>"ECOBIO - Écosystèmes, biodiversité, évolution (ECOBIO)",
"EMPENN-R" =>"EMPENN (ex VISAGES)",
"ETHOS" =>"EthoS - Éthologie animale et humaine (EthoS)",
"FOTON" =>"FOTON - Fonctions optiques pour les technologies de l'information (FOTON)",
"BIODIV" =>"Géoarchitecture - EA 7462 - Géoarchitecture : Territoires, Urbanisation, Biodiversité, Environnement",
"GR" =>"Géosciences Rennes",
"IDPSP" =>"IDPSP -Institut du droit public et de la science politique (IDPSP)",
"IETR" =>"IETR - Institut d'électronique et de télécommunications de Rennes (IETR)",
"IGDR" =>"IGDR - Institut de génétique et développement de Rennes (IGDR)",
"IGEPP" =>"IGEPP - Institut de génétique, environnement et protection des plantes (IGEPP)",
"IODE" =>"IODE - Institut de l'Ouest : droit et Europe (IODE)",
"IPR" =>"IPR - Institut de physique de Rennes (IPR)",
"IRISA" =>"IRISA - Institut de recherche en informatique et systèmes aléatoires (IRISA)",
"IRMAR" =>"IRMAR - Institut de recherche mathématique de Rennes (IRMAR)",
"IRSET" =>"Irset - Institut de recherche en santé, environnement et travail (IRSET)",
"ISCR" =>"ISCR - Institut des sciences chimiques de Rennes (ISCR)",
"LGCGM" =>"LGCGM - Laboratoire de génie civil et génie mécanique (LGCGM)",
"LTSI" =>"LTSI - Laboratoire traitement du signal et de l'image (LTSI)",
"M2S" =>"M2S - Laboratoire mouvement, sport et santé (M2S)",
"U917" =>"MICMAC - Microenvironment, Cell Differentiation, Immunology and Cancer (MICMAC)",
"NUMECAN" =>"NUMECAN - Nutrition, Métabolismes et Cancer (NUMECAN)",
"OSUR" =>"OSUR - Observatoire des Sciences de l'Univers de Rennes (OSUR)",
"REPERES" =>"Repères - Recherche en Pharmaco-épidémiologie et Recours aux Soins (Repères)",
"UNIV-RENNES1"=>"Université de Rennes 1",
"UNIV-RENNES"=>"Université de Rennes"
);
?>
